/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/hello-world/hello-world.vue')['default']
    IEpClock: typeof import('~icons/ep/clock')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMessage: typeof import('~icons/ep/message')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XfFormList: typeof import('./src/components/xf-form-list/xf-form-list.vue')['default']
    XfFormTable: typeof import('./src/components/xf-form-table/xf-form-table.vue')['default']
    XfSelectGet: typeof import('./src/components/xf-select-get/xf-select-get.vue')['default']
    XfSelectSearch: typeof import('./src/components/xf-select-search/xf-select-search.vue')['default']
    XfTableList: typeof import('./src/components/xf-table-list/xf-table-list.vue')['default']
  }
}
